- endpoint: https://www.dogfactsapi.ducnguyen.dev/api/v1/facts/?number=3
  method: GET
  status: 200
  asserts:
   - path: facts.length
     value: 3
- endpoint: https://api.sampleapis.com/coffee/hot
  method: POST
  body:
    title: wrong
  status: 200
  asserts:
   - path: error
     value: 400
